export const user = {
  info: {
    status: "OK",
    result: [
      {
        contribution: 0,
        lastOnlineTimeSeconds: 1712642700,
        rating: 1386,
        friendOfCount: 1,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        rank: "pupil",
        handle: "redheadphone3",
        maxRating: 1386,
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1710439345,
        maxRank: "pupil",
      },
    ],
  },
  rating: {
    status: "OK",
    result: [
      {
        contestId: 1948,
        contestName: "Educational Codeforces Round 163 (Rated for Div. 2)",
        handle: "redheadphone3",
        rank: 2269,
        ratingUpdateTimeSeconds: 1710520500,
        oldRating: 0,
        newRating: 570,
      },
      {
        contestId: 1944,
        contestName: "Codeforces Round 934 (Div. 2)",
        handle: "redheadphone3",
        rank: 4504,
        ratingUpdateTimeSeconds: 1710608400,
        oldRating: 570,
        newRating: 882,
      },
      {
        contestId: 1945,
        contestName: "Codeforces Round 935 (Div. 3)",
        handle: "redheadphone3",
        rank: 1019,
        ratingUpdateTimeSeconds: 1710843600,
        oldRating: 882,
        newRating: 1175,
      },
      {
        contestId: 1942,
        contestName: "CodeTON Round 8 (Div. 1 + Div. 2, Rated, Prizes!)",
        handle: "redheadphone3",
        rank: 5434,
        ratingUpdateTimeSeconds: 1711820100,
        oldRating: 1175,
        newRating: 1275,
      },
      {
        contestId: 1951,
        contestName: "Codeforces Global Round 25",
        handle: "redheadphone3",
        rank: 3890,
        ratingUpdateTimeSeconds: 1712424900,
        oldRating: 1275,
        newRating: 1386,
      },
    ],
  },
  status: {
    status: "OK",
    result: [
      {
        id: 255364586,
        contestId: 1951,
        creationTimeSeconds: 1712427826,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1951,
          index: "D",
          name: "Buying Jewels",
          type: "PROGRAMMING",
          points: 1750.0,
          rating: 2000,
          tags: ["constructive algorithms", "greedy", "math"],
        },
        author: {
          contestId: 1951,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1712414100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "TESTS",
        passedTestCount: 1,
        timeConsumedMillis: 187,
        memoryConsumedBytes: 9523200,
      },
      {
        id: 255336667,
        contestId: 1951,
        creationTimeSeconds: 1712421334,
        relativeTimeSeconds: 7234,
        problem: {
          contestId: 1951,
          index: "C",
          name: "Ticket Hoarding",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1400,
          tags: ["greedy", "math", "sortings"],
        },
        author: {
          contestId: 1951,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 399,
          startTimeSeconds: 1712414100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 21,
        timeConsumedMillis: 1265,
        memoryConsumedBytes: 51609600,
      },
      {
        id: 255334880,
        contestId: 1951,
        creationTimeSeconds: 1712421065,
        relativeTimeSeconds: 6965,
        problem: {
          contestId: 1951,
          index: "C",
          name: "Ticket Hoarding",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1400,
          tags: ["greedy", "math", "sortings"],
        },
        author: {
          contestId: 1951,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 399,
          startTimeSeconds: 1712414100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "PRETESTS",
        passedTestCount: 1,
        timeConsumedMillis: 390,
        memoryConsumedBytes: 10854400,
      },
      {
        id: 255327871,
        contestId: 1951,
        creationTimeSeconds: 1712420108,
        relativeTimeSeconds: 6008,
        problem: {
          contestId: 1951,
          index: "B",
          name: "Battle Cows",
          type: "PROGRAMMING",
          points: 1000.0,
          rating: 1200,
          tags: ["binary search", "data structures", "greedy"],
        },
        author: {
          contestId: 1951,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 399,
          startTimeSeconds: 1712414100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 13,
        timeConsumedMillis: 577,
        memoryConsumedBytes: 17305600,
      },
      {
        id: 255318932,
        contestId: 1951,
        creationTimeSeconds: 1712418991,
        relativeTimeSeconds: 4891,
        problem: {
          contestId: 1951,
          index: "A",
          name: "Dual Trigger",
          type: "PROGRAMMING",
          points: 500.0,
          rating: 900,
          tags: ["constructive algorithms", "greedy", "math"],
        },
        author: {
          contestId: 1951,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 399,
          startTimeSeconds: 1712414100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 3,
        timeConsumedMillis: 155,
        memoryConsumedBytes: 5427200,
      },
      {
        id: 254267932,
        contestId: 1942,
        creationTimeSeconds: 1711872646,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1942,
          index: "C2",
          name: "Bessie\u0027s Birthday Cake (Hard Version)",
          type: "PROGRAMMING",
          points: 750.0,
          rating: 1700,
          tags: ["geometry", "greedy", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 15,
        timeConsumedMillis: 640,
        memoryConsumedBytes: 35430400,
      },
      {
        id: 254187208,
        contestId: 1942,
        creationTimeSeconds: 1711818030,
        relativeTimeSeconds: 8730,
        problem: {
          contestId: 1942,
          index: "C1",
          name: "Bessie\u0027s Birthday Cake (Easy Version)",
          type: "PROGRAMMING",
          points: 1250.0,
          rating: 1300,
          tags: ["geometry", "greedy", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 268,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 15,
        timeConsumedMillis: 343,
        memoryConsumedBytes: 35225600,
      },
      {
        id: 254186020,
        contestId: 1942,
        creationTimeSeconds: 1711817807,
        relativeTimeSeconds: 8507,
        problem: {
          contestId: 1942,
          index: "C1",
          name: "Bessie\u0027s Birthday Cake (Easy Version)",
          type: "PROGRAMMING",
          points: 1250.0,
          rating: 1300,
          tags: ["geometry", "greedy", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 268,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "TIME_LIMIT_EXCEEDED",
        testset: "PRETESTS",
        passedTestCount: 5,
        timeConsumedMillis: 2000,
        memoryConsumedBytes: 14028800,
      },
      {
        id: 254185625,
        contestId: 1942,
        creationTimeSeconds: 1711817736,
        relativeTimeSeconds: 8436,
        problem: {
          contestId: 1942,
          index: "C1",
          name: "Bessie\u0027s Birthday Cake (Easy Version)",
          type: "PROGRAMMING",
          points: 1250.0,
          rating: 1300,
          tags: ["geometry", "greedy", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 268,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "TIME_LIMIT_EXCEEDED",
        testset: "PRETESTS",
        passedTestCount: 5,
        timeConsumedMillis: 2000,
        memoryConsumedBytes: 12492800,
      },
      {
        id: 254177996,
        contestId: 1942,
        creationTimeSeconds: 1711816373,
        relativeTimeSeconds: 7073,
        problem: {
          contestId: 1942,
          index: "B",
          name: "Bessie and MEX",
          type: "PROGRAMMING",
          points: 1000.0,
          rating: 1100,
          tags: ["constructive algorithms", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 268,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 20,
        timeConsumedMillis: 405,
        memoryConsumedBytes: 36966400,
      },
      {
        id: 254177328,
        contestId: 1942,
        creationTimeSeconds: 1711816265,
        relativeTimeSeconds: 6965,
        problem: {
          contestId: 1942,
          index: "B",
          name: "Bessie and MEX",
          type: "PROGRAMMING",
          points: 1000.0,
          rating: 1100,
          tags: ["constructive algorithms", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 268,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "PRETESTS",
        passedTestCount: 1,
        timeConsumedMillis: 373,
        memoryConsumedBytes: 13414400,
      },
      {
        id: 254175631,
        contestId: 1942,
        creationTimeSeconds: 1711816000,
        relativeTimeSeconds: 6700,
        problem: {
          contestId: 1942,
          index: "B",
          name: "Bessie and MEX",
          type: "PROGRAMMING",
          points: 1000.0,
          rating: 1100,
          tags: ["constructive algorithms", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 268,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "PRETESTS",
        passedTestCount: 1,
        timeConsumedMillis: 358,
        memoryConsumedBytes: 13619200,
      },
      {
        id: 254174818,
        contestId: 1942,
        creationTimeSeconds: 1711815861,
        relativeTimeSeconds: 6561,
        problem: {
          contestId: 1942,
          index: "B",
          name: "Bessie and MEX",
          type: "PROGRAMMING",
          points: 1000.0,
          rating: 1100,
          tags: ["constructive algorithms", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 268,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "PRETESTS",
        passedTestCount: 1,
        timeConsumedMillis: 358,
        memoryConsumedBytes: 14540800,
      },
      {
        id: 254160690,
        contestId: 1942,
        creationTimeSeconds: 1711813740,
        relativeTimeSeconds: 4440,
        problem: {
          contestId: 1942,
          index: "A",
          name: "Farmer John\u0027s Challenge",
          type: "PROGRAMMING",
          points: 500.0,
          rating: 800,
          tags: ["constructive algorithms", "math"],
        },
        author: {
          contestId: 1942,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 268,
          startTimeSeconds: 1711809300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 5,
        timeConsumedMillis: 155,
        memoryConsumedBytes: 11264000,
      },
      {
        id: 253228472,
        contestId: 1946,
        creationTimeSeconds: 1711377644,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "D",
          name: "Birthday Gift",
          type: "PROGRAMMING",
          points: 1750.0,
          rating: 1900,
          tags: [
            "bitmasks",
            "brute force",
            "constructive algorithms",
            "greedy",
            "implementation",
          ],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 23,
        timeConsumedMillis: 295,
        memoryConsumedBytes: 19251200,
      },
      {
        id: 253227703,
        contestId: 1946,
        creationTimeSeconds: 1711377318,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "D",
          name: "Birthday Gift",
          type: "PROGRAMMING",
          points: 1750.0,
          rating: 1900,
          tags: [
            "bitmasks",
            "brute force",
            "constructive algorithms",
            "greedy",
            "implementation",
          ],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "TESTS",
        passedTestCount: 5,
        timeConsumedMillis: 265,
        memoryConsumedBytes: 14540800,
      },
      {
        id: 253175742,
        contestId: 1759,
        creationTimeSeconds: 1711353785,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1759,
          index: "G",
          name: "Restore the Permutation",
          type: "PROGRAMMING",
          rating: 1900,
          tags: [
            "binary search",
            "constructive algorithms",
            "data structures",
            "greedy",
            "math",
          ],
        },
        author: {
          contestId: 1759,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1668782100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 36,
        timeConsumedMillis: 545,
        memoryConsumedBytes: 29388800,
      },
      {
        id: 253174615,
        contestId: 1759,
        creationTimeSeconds: 1711353061,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1759,
          index: "G",
          name: "Restore the Permutation",
          type: "PROGRAMMING",
          rating: 1900,
          tags: [
            "binary search",
            "constructive algorithms",
            "data structures",
            "greedy",
            "math",
          ],
        },
        author: {
          contestId: 1759,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1668782100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 36,
        timeConsumedMillis: 561,
        memoryConsumedBytes: 30003200,
      },
      {
        id: 253174442,
        contestId: 1759,
        creationTimeSeconds: 1711352964,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1759,
          index: "G",
          name: "Restore the Permutation",
          type: "PROGRAMMING",
          rating: 1900,
          tags: [
            "binary search",
            "constructive algorithms",
            "data structures",
            "greedy",
            "math",
          ],
        },
        author: {
          contestId: 1759,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1668782100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "RUNTIME_ERROR",
        testset: "TESTS",
        passedTestCount: 0,
        timeConsumedMillis: 77,
        memoryConsumedBytes: 4300800,
      },
      {
        id: 253068633,
        contestId: 1946,
        creationTimeSeconds: 1711277330,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "D",
          name: "Birthday Gift",
          type: "PROGRAMMING",
          points: 1750.0,
          rating: 1900,
          tags: [
            "bitmasks",
            "brute force",
            "constructive algorithms",
            "greedy",
            "implementation",
          ],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "TESTS",
        passedTestCount: 3,
        timeConsumedMillis: 171,
        memoryConsumedBytes: 10752000,
      },
      {
        id: 253068493,
        contestId: 1946,
        creationTimeSeconds: 1711277271,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "D",
          name: "Birthday Gift",
          type: "PROGRAMMING",
          points: 1750.0,
          rating: 1900,
          tags: [
            "bitmasks",
            "brute force",
            "constructive algorithms",
            "greedy",
            "implementation",
          ],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "TESTS",
        passedTestCount: 3,
        timeConsumedMillis: 186,
        memoryConsumedBytes: 9523200,
      },
      {
        id: 253068319,
        contestId: 1946,
        creationTimeSeconds: 1711277191,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "D",
          name: "Birthday Gift",
          type: "PROGRAMMING",
          points: 1750.0,
          rating: 1900,
          tags: [
            "bitmasks",
            "brute force",
            "constructive algorithms",
            "greedy",
            "implementation",
          ],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "TESTS",
        passedTestCount: 1,
        timeConsumedMillis: 155,
        memoryConsumedBytes: 9216000,
      },
      {
        id: 253067504,
        contestId: 1946,
        creationTimeSeconds: 1711276837,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "D",
          name: "Birthday Gift",
          type: "PROGRAMMING",
          points: 1750.0,
          rating: 1900,
          tags: [
            "bitmasks",
            "brute force",
            "constructive algorithms",
            "greedy",
            "implementation",
          ],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "TESTS",
        passedTestCount: 1,
        timeConsumedMillis: 171,
        memoryConsumedBytes: 9216000,
      },
      {
        id: 253062833,
        contestId: 1946,
        creationTimeSeconds: 1711274794,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "C",
          name: "Tree Cutting",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1600,
          tags: ["binary search", "dp", "greedy", "implementation", "trees"],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 27,
        timeConsumedMillis: 1902,
        memoryConsumedBytes: 126873600,
      },
      {
        id: 253062714,
        contestId: 1946,
        creationTimeSeconds: 1711274741,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "C",
          name: "Tree Cutting",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1600,
          tags: ["binary search", "dp", "greedy", "implementation", "trees"],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "RUNTIME_ERROR",
        testset: "TESTS",
        passedTestCount: 0,
        timeConsumedMillis: 93,
        memoryConsumedBytes: 4915200,
      },
      {
        id: 253062623,
        contestId: 1946,
        creationTimeSeconds: 1711274701,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "C",
          name: "Tree Cutting",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1600,
          tags: ["binary search", "dp", "greedy", "implementation", "trees"],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "RUNTIME_ERROR",
        testset: "TESTS",
        passedTestCount: 4,
        timeConsumedMillis: 654,
        memoryConsumedBytes: 37580800,
      },
      {
        id: 253059224,
        contestId: 1946,
        creationTimeSeconds: 1711272915,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "B",
          name: "Maximum Sum",
          type: "PROGRAMMING",
          points: 1000.0,
          rating: 1100,
          tags: ["dp", "greedy", "math"],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 14,
        timeConsumedMillis: 233,
        memoryConsumedBytes: 32460800,
      },
      {
        id: 253058357,
        contestId: 1946,
        creationTimeSeconds: 1711272461,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1946,
          index: "A",
          name: "Median of an Array",
          type: "PROGRAMMING",
          points: 500.0,
          rating: 800,
          tags: ["greedy", "implementation", "sortings"],
        },
        author: {
          contestId: 1946,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1711118100,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 8,
        timeConsumedMillis: 186,
        memoryConsumedBytes: 23654400,
      },
      {
        id: 252289944,
        contestId: 1945,
        creationTimeSeconds: 1710850810,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1945,
          index: "D",
          name: "Seraphim the Owl",
          type: "PROGRAMMING",
          rating: 1300,
          tags: ["dp", "greedy"],
        },
        author: {
          contestId: 1945,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1710835500,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "TIME_LIMIT_EXCEEDED",
        testset: "TESTS",
        passedTestCount: 2,
        timeConsumedMillis: 2000,
        memoryConsumedBytes: 10956800,
      },
      {
        id: 252267013,
        contestId: 1945,
        creationTimeSeconds: 1710843442,
        relativeTimeSeconds: 7942,
        problem: {
          contestId: 1945,
          index: "E",
          name: "Binary Search",
          type: "PROGRAMMING",
          rating: 1700,
          tags: ["binary search", "constructive algorithms", "greedy"],
        },
        author: {
          contestId: 1945,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710835500,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 17,
        timeConsumedMillis: 327,
        memoryConsumedBytes: 29081600,
      },
      {
        id: 252244620,
        contestId: 1945,
        creationTimeSeconds: 1710840569,
        relativeTimeSeconds: 5069,
        problem: {
          contestId: 1945,
          index: "D",
          name: "Seraphim the Owl",
          type: "PROGRAMMING",
          rating: 1300,
          tags: ["dp", "greedy"],
        },
        author: {
          contestId: 1945,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710835500,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 32,
        timeConsumedMillis: 421,
        memoryConsumedBytes: 44748800,
      },
      {
        id: 252241333,
        contestId: 1945,
        creationTimeSeconds: 1710840180,
        relativeTimeSeconds: 4680,
        problem: {
          contestId: 1945,
          index: "D",
          name: "Seraphim the Owl",
          type: "PROGRAMMING",
          rating: 1300,
          tags: ["dp", "greedy"],
        },
        author: {
          contestId: 1945,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710835500,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "RUNTIME_ERROR",
        testset: "TESTS",
        passedTestCount: 4,
        timeConsumedMillis: 1076,
        memoryConsumedBytes: 15257600,
      },
      {
        id: 252234707,
        contestId: 1945,
        creationTimeSeconds: 1710839419,
        relativeTimeSeconds: 3919,
        problem: {
          contestId: 1945,
          index: "C",
          name: "Left and Right Houses",
          type: "PROGRAMMING",
          rating: 1200,
          tags: ["brute force"],
        },
        author: {
          contestId: 1945,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710835500,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 12,
        timeConsumedMillis: 265,
        memoryConsumedBytes: 13107200,
      },
      {
        id: 252224611,
        contestId: 1945,
        creationTimeSeconds: 1710838337,
        relativeTimeSeconds: 2837,
        problem: {
          contestId: 1945,
          index: "B",
          name: "Fireworks",
          type: "PROGRAMMING",
          rating: 900,
          tags: ["math", "number theory"],
        },
        author: {
          contestId: 1945,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710835500,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 7,
        timeConsumedMillis: 124,
        memoryConsumedBytes: 9728000,
      },
      {
        id: 252220572,
        contestId: 1945,
        creationTimeSeconds: 1710837939,
        relativeTimeSeconds: 2439,
        problem: {
          contestId: 1945,
          index: "A",
          name: "Setting up Camp",
          type: "PROGRAMMING",
          rating: 800,
          tags: ["greedy", "math"],
        },
        author: {
          contestId: 1945,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710835500,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 8,
        timeConsumedMillis: 217,
        memoryConsumedBytes: 11878400,
      },
      {
        id: 251771221,
        contestId: 1944,
        creationTimeSeconds: 1710605462,
        relativeTimeSeconds: 5762,
        problem: {
          contestId: 1944,
          index: "C",
          name: "MEX Game 1",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1300,
          tags: ["constructive algorithms", "games", "greedy"],
        },
        author: {
          contestId: 1944,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 375,
          startTimeSeconds: 1710599700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 20,
        timeConsumedMillis: 327,
        memoryConsumedBytes: 30720000,
      },
      {
        id: 251769126,
        contestId: 1944,
        creationTimeSeconds: 1710605209,
        relativeTimeSeconds: 5509,
        problem: {
          contestId: 1944,
          index: "C",
          name: "MEX Game 1",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1300,
          tags: ["constructive algorithms", "games", "greedy"],
        },
        author: {
          contestId: 1944,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 375,
          startTimeSeconds: 1710599700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "PRETESTS",
        passedTestCount: 1,
        timeConsumedMillis: 249,
        memoryConsumedBytes: 14745600,
      },
      {
        id: 251767723,
        contestId: 1944,
        creationTimeSeconds: 1710605047,
        relativeTimeSeconds: 5347,
        problem: {
          contestId: 1944,
          index: "C",
          name: "MEX Game 1",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1300,
          tags: ["constructive algorithms", "games", "greedy"],
        },
        author: {
          contestId: 1944,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 375,
          startTimeSeconds: 1710599700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "PRETESTS",
        passedTestCount: 1,
        timeConsumedMillis: 311,
        memoryConsumedBytes: 11980800,
      },
      {
        id: 251762701,
        contestId: 1944,
        creationTimeSeconds: 1710604501,
        relativeTimeSeconds: 4801,
        problem: {
          contestId: 1944,
          index: "C",
          name: "MEX Game 1",
          type: "PROGRAMMING",
          points: 1500.0,
          rating: 1300,
          tags: ["constructive algorithms", "games", "greedy"],
        },
        author: {
          contestId: 1944,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 375,
          startTimeSeconds: 1710599700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "PRETESTS",
        passedTestCount: 1,
        timeConsumedMillis: 249,
        memoryConsumedBytes: 11571200,
      },
      {
        id: 251760013,
        contestId: 1944,
        creationTimeSeconds: 1710604227,
        relativeTimeSeconds: 4527,
        problem: {
          contestId: 1944,
          index: "B",
          name: "Equal XOR",
          type: "PROGRAMMING",
          points: 1000.0,
          rating: 1100,
          tags: ["bitmasks", "constructive algorithms"],
        },
        author: {
          contestId: 1944,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 375,
          startTimeSeconds: 1710599700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 14,
        timeConsumedMillis: 545,
        memoryConsumedBytes: 23449600,
      },
      {
        id: 251755574,
        contestId: 1944,
        creationTimeSeconds: 1710603785,
        relativeTimeSeconds: 4085,
        problem: {
          contestId: 1944,
          index: "A",
          name: "Destroying Bridges",
          type: "PROGRAMMING",
          points: 500.0,
          rating: 800,
          tags: ["graphs", "greedy", "math"],
        },
        author: {
          contestId: 1944,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          room: 375,
          startTimeSeconds: 1710599700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 4,
        timeConsumedMillis: 139,
        memoryConsumedBytes: 4710400,
      },
      {
        id: 251673277,
        contestId: 1921,
        creationTimeSeconds: 1710587619,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1921,
          index: "C",
          name: "Sending Messages",
          type: "PROGRAMMING",
          rating: 900,
          tags: ["greedy", "math"],
        },
        author: {
          contestId: 1921,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1705329300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 11,
        timeConsumedMillis: 248,
        memoryConsumedBytes: 35532800,
      },
      {
        id: 251670884,
        contestId: 1702,
        creationTimeSeconds: 1710586602,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1702,
          index: "E",
          name: "Split Into Two Sets",
          type: "PROGRAMMING",
          rating: 1600,
          tags: ["dfs and similar", "dsu", "graphs"],
        },
        author: {
          contestId: 1702,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1657463700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 13,
        timeConsumedMillis: 732,
        memoryConsumedBytes: 27852800,
      },
      {
        id: 251669881,
        contestId: 1702,
        creationTimeSeconds: 1710586191,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1702,
          index: "E",
          name: "Split Into Two Sets",
          type: "PROGRAMMING",
          rating: 1600,
          tags: ["dfs and similar", "dsu", "graphs"],
        },
        author: {
          contestId: 1702,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1657463700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 13,
        timeConsumedMillis: 498,
        memoryConsumedBytes: 19046400,
      },
      {
        id: 251669278,
        contestId: 1702,
        creationTimeSeconds: 1710585938,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1702,
          index: "E",
          name: "Split Into Two Sets",
          type: "PROGRAMMING",
          rating: 1600,
          tags: ["dfs and similar", "dsu", "graphs"],
        },
        author: {
          contestId: 1702,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1657463700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "TIME_LIMIT_EXCEEDED",
        testset: "TESTS",
        passedTestCount: 11,
        timeConsumedMillis: 2000,
        memoryConsumedBytes: 30310400,
      },
      {
        id: 251668638,
        contestId: 1702,
        creationTimeSeconds: 1710585669,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1702,
          index: "E",
          name: "Split Into Two Sets",
          type: "PROGRAMMING",
          rating: 1600,
          tags: ["dfs and similar", "dsu", "graphs"],
        },
        author: {
          contestId: 1702,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1657463700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "TIME_LIMIT_EXCEEDED",
        testset: "TESTS",
        passedTestCount: 11,
        timeConsumedMillis: 2000,
        memoryConsumedBytes: 31948800,
      },
      {
        id: 251668153,
        contestId: 1702,
        creationTimeSeconds: 1710585450,
        relativeTimeSeconds: 2147483647,
        problem: {
          contestId: 1702,
          index: "E",
          name: "Split Into Two Sets",
          type: "PROGRAMMING",
          rating: 1600,
          tags: ["dfs and similar", "dsu", "graphs"],
        },
        author: {
          contestId: 1702,
          members: [{ handle: "redheadphone3" }],
          participantType: "PRACTICE",
          ghost: false,
          startTimeSeconds: 1657463700,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "RUNTIME_ERROR",
        testset: "TESTS",
        passedTestCount: 1,
        timeConsumedMillis: 78,
        memoryConsumedBytes: 4198400,
      },
      {
        id: 251532081,
        contestId: 1948,
        creationTimeSeconds: 1710519889,
        relativeTimeSeconds: 6589,
        problem: {
          contestId: 1948,
          index: "D",
          name: "Tandem Repeats?",
          type: "PROGRAMMING",
          rating: 1700,
          tags: ["brute force", "strings", "two pointers"],
        },
        author: {
          contestId: 1948,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710513300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 69,
        timeConsumedMillis: 265,
        memoryConsumedBytes: 5836800,
      },
      {
        id: 251525611,
        contestId: 1948,
        creationTimeSeconds: 1710519312,
        relativeTimeSeconds: 6012,
        problem: {
          contestId: 1948,
          index: "C",
          name: "Arrow Path",
          type: "PROGRAMMING",
          rating: 1300,
          tags: [
            "brute force",
            "constructive algorithms",
            "dfs and similar",
            "dp",
            "graphs",
            "shortest paths",
          ],
        },
        author: {
          contestId: 1948,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710513300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 22,
        timeConsumedMillis: 296,
        memoryConsumedBytes: 29184000,
      },
      {
        id: 251521337,
        contestId: 1948,
        creationTimeSeconds: 1710518926,
        relativeTimeSeconds: 5626,
        problem: {
          contestId: 1948,
          index: "B",
          name: "Array Fix",
          type: "PROGRAMMING",
          rating: 1100,
          tags: ["brute force", "dp", "greedy", "implementation"],
        },
        author: {
          contestId: 1948,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710513300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 6,
        timeConsumedMillis: 186,
        memoryConsumedBytes: 7884800,
      },
      {
        id: 251509122,
        contestId: 1948,
        creationTimeSeconds: 1710517955,
        relativeTimeSeconds: 4655,
        problem: {
          contestId: 1948,
          index: "B",
          name: "Array Fix",
          type: "PROGRAMMING",
          rating: 1100,
          tags: ["brute force", "dp", "greedy", "implementation"],
        },
        author: {
          contestId: 1948,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710513300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "WRONG_ANSWER",
        testset: "TESTS",
        passedTestCount: 1,
        timeConsumedMillis: 124,
        memoryConsumedBytes: 5529600,
      },
      {
        id: 251503979,
        contestId: 1948,
        creationTimeSeconds: 1710517573,
        relativeTimeSeconds: 4273,
        problem: {
          contestId: 1948,
          index: "A",
          name: "Special Characters",
          type: "PROGRAMMING",
          rating: 800,
          tags: ["brute force", "constructive algorithms"],
        },
        author: {
          contestId: 1948,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710513300,
        },
        programmingLanguage: "PyPy 3-64",
        verdict: "OK",
        testset: "TESTS",
        passedTestCount: 2,
        timeConsumedMillis: 77,
        memoryConsumedBytes: 2764800,
      },
      {
        id: 251501833,
        contestId: 1948,
        creationTimeSeconds: 1710517435,
        relativeTimeSeconds: 4135,
        problem: {
          contestId: 1948,
          index: "A",
          name: "Special Characters",
          type: "PROGRAMMING",
          rating: 800,
          tags: ["brute force", "constructive algorithms"],
        },
        author: {
          contestId: 1948,
          members: [{ handle: "redheadphone3" }],
          participantType: "CONTESTANT",
          ghost: false,
          startTimeSeconds: 1710513300,
        },
        programmingLanguage: "GNU C11",
        verdict: "COMPILATION_ERROR",
        testset: "TESTS",
        passedTestCount: 0,
        timeConsumedMillis: 0,
        memoryConsumedBytes: 0,
      },
    ],
  },
};
